# Supabase Configuration File

project_id = "yjyptluxhubjmbbakdld"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-app.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "5MB"

[functions.analyze-resume]
verify_jwt = true

[functions.optimize-resume]
verify_jwt = true

[functions.generate-interview-questions]
verify_jwt = true

[functions.analyze-interview-response]
verify_jwt = true