project_id = "yjyptluxhubjmbbakdld"

[functions.analyze-resume]
verify_jwt = true

[functions.optimize-resume]
verify_jwt = true

[functions.generate-interview-questions]
verify_jwt = true

[functions.analyze-interview-response]
verify_jwt = true