version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: careerai_db
    environment:
      POSTGRES_DB: careerai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: careerai_ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # Optional: For GPU acceleration

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: careerai_backend
    environment:
      DATABASE_URL: postgresql://admin:dev_password@postgres:5432/careerai
      OLLAMA_URL: http://ollama:11434
      JWT_SECRET: dev_secret_key_change_in_production
      UPLOAD_DIR: /app/uploads
    volumes:
      - ../../backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: careerai_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  ollama_data:
  backend_uploads: